# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- group: imagebuilder

steps:
#- checkout: self


- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'anugrah pay as you go(cbf8b966-9488-4fc7-a133-b65c3b0285a8)'
    subscriptionId: '$(subscription)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourcegroup)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: 'ARM Template for Image/Galleryimagename.json'
    csmParametersFile: 'ARM Template for Image/parametersgallery.json'
    deploymentMode: 'Incremental'

# - task: AzureResourceManagerTemplateDeployment@3
#   inputs:
#     deploymentScope: 'Resource Group'
#     azureResourceManagerConnection: 'anugrah pay as you go(cbf8b966-9488-4fc7-a133-b65c3b0285a8)'
#     subscriptionId: '$(subscription)'
#     action: 'Create Or Update Resource Group'
#     resourceGroupName: '$(resourcegroup)'
#     location: '$(location)'
#     templateLocation: 'Linked artifact'
#     csmFile: 'ARM Template for Image /Linuxtemplate.json'
#     csmParametersFile: 'ARM Template for Image /Linuxparameters.json'
#     deploymentMode: 'Incremental'